name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  # 只有向 main 分支推送代码时才触发部署

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 极其关键：必须加上这行，GitHub 编译时才会去抓取你刚才添加的主题子模块
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Hugo
        uses: actions/setup-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true         # 很多主题（包括 moments）需要 extended 版本来处理 CSS 样式

      - name: Build with Hugo
        run: hugo --gc --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

